export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <header
        style={{
          backgroundColor: "blue",
          padding: "1rem",
        }}
      >
        Header
      </header>
      <body>{children}</body>
      <footer
        style={{
          backgroundColor: "GrayText",
          padding: "1rem",
        }}
      >
        Footer
      </footer>
    </html>
  );
}
